apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nextjs-app
  labels:
    release: prometheus  # adjust to your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app: nextjs-app
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
